### ISSUE TITLE
巧妙利用CSS做一些常见效果

### ISSUE THREAD

**Issue by askwuxue** [askwuxue/blog#14]
#### 1. 使用CSS画圆
<img width="871" alt="image" src="https://github.com/askwuxue/blog/assets/32808762/fdc348d9-7314-4fc8-b8fb-6bf41d809ed7">

```html
<div class="pie"></div>
```

```
.pie {
  display: inline-block;
  width: 150px;
  height: 150px;
  border-radius: 50%;
  background: #3c7;
}
```

#### 2. 使用CSS画扇形图
<img width="877" alt="image" src="https://github.com/askwuxue/blog/assets/32808762/996017d6-1d5d-446e-a905-6f9d1ba11d53">

```css
.pie {
  display: inline-block;
  width: 0;
  height: 0;
  border-radius: 50%;
  border: solid 75px;
  border-color: red blue orange green;
  box-sizing: border-box;
}
```
