### ISSUE TITLE
巧妙利用CSS做一些常见效果

### ISSUE THREAD

**Issue by askwuxue** [askwuxue/blog#15]
#### 1. 使用CSS画圆
```html
<div class="pie"></div>
```
```css
.pie {
  display: inline-block;
  width: 150px;
  height: 150px;
  border-radius: 50%;
  background: #3c7;
}
```

<img width="871" alt="image" src="https://github.com/askwuxue/blog/assets/32808762/fdc348d9-7314-4fc8-b8fb-6bf41d809ed7">
