### ISSUE TITLE
-webkit-line-clamp 显示省略...

### ISSUE THREAD

**Issue by askwuxue** [askwuxue/blog#5]
-webkit-line-clamp CSS 属性可以把[块容器](https://developer.mozilla.org/zh-CN/docs/Glossary/Block)中的内容限制为指定的行数

它只有在 [display](https://developer.mozilla.org/zh-CN/docs/Web/CSS/display) 属性设置成 -webkit-box 或者 -webkit-inline-box 并且 [box-orient](https://developer.mozilla.org/zh-CN/docs/Web/CSS/box-orient) 属性设置成 vertical时才有效果。

在大部分情况下，也需要设置 [overflow](https://developer.mozilla.org/zh-CN/docs/Web/CSS/overflow) 属性为 hidden，否则，里面的内容不会被裁减，并且在内容显示为指定行数后还会显示省略号。

CSS代码：
```css
.box {
    width: 400px; 
    display: -webkit-box;
    -webkit-line-clamp: 3;
    -webkit-box-orient: vertical;
    overflow: hidden;
}
```
HTML代码：
```html
<div class="box">
    【在此示例中，<code>-webkit-line-clamp</code> 属性设置为 <code>2</code>，即文本在超过两行后将被截断。文本截断处将显示省略号。
</div>
```
