### ISSUE TITLE
antd button 点击清除四周的光晕效果

### ISSUE THREAD

**Issue by askwuxue** [askwuxue/blog#8]
```css
button[ant-click-animating-without-extra-node]:after {
  border: 0 none;
  opacity: 0;
  animation:none;
  outline:none;
}
```
